apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rsenvcomp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: POC
          value: POC
        image: quay.io/abarbaro-org/spi-demos-nenp-tenant/rsenvapp/rsenvcomp@sha256:11bcea164f634b8dae42dcc42ef571bcb4c580b9b158fa0c3840a329c1c19210
        name: my-java-quarkus
        resources: {}
status: {}
